// src/lib/components/Header.svelte
<script lang="ts">
  import { Menu, Search, X } from "lucide-svelte";
  import { Button } from "$lib/components/ui/button";
  import { slide } from "svelte/transition";
  import { page } from "$app/stores";

  let isMenuOpen = false;
  let searchQuery = "";

  const categories = [
    { id: "mouse", label: "Mouse" },
    { id: "mousepad", label: "Mousepad" },
    { id: "keyboard", label: "Keyboard" },
  ];

  const socialLinks = [
    { href: "#", label: "TikTok" },
    { href: "#", label: "Instagram" },
    { href: "#", label: "Discord" },
  ];
</script>

<header class="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur">
  <div class="container flex h-14 items-center">
    <Button
      variant="ghost"
      size="icon"
      class="touch-target md:hidden"
      on:click={() => (isMenuOpen = !isMenuOpen)}
    >
      {#if isMenuOpen}
        <X class="h-5 w-5" />
      {:else}
        <Menu class="h-5 w-5" />
      {/if}
    </Button>

    <div class="flex flex-1 items-center justify-between space-x-2 md:justify-end">
      <form
        class="w-full md:w-auto md:flex-1 md:max-w-sm"
        on:submit|preventDefault
      >
        <div class="relative">
          <Search class="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
          <input
            type="search"
            placeholder="Search products..."
            class="w-full rounded-md border bg-background px-8 py-2 text-sm"
            bind:value={searchQuery}
          />
        </div>
      </form>
    </div>
  </div>

  {#if isMenuOpen}
    <div
      class="container pb-4"
      transition:slide={{ duration: 200 }}
    >
      <nav class="flex flex-col space-y-4">
        <div class="flex flex-wrap gap-2">
          {#each categories as category}
            <a
              href="/{category.id}"
              class="rounded-full bg-muted px-4 py-1.5 text-sm font-medium
                {$page.url.pathname === `/${category.id}` ? 'bg-primary text-primary-foreground' : ''}"
            >
              {category.label}
            </a>
          {/each}
        </div>

        <div class="flex flex-wrap gap-4">
          {#each socialLinks as link}
            <a
              href={link.href}
              class="text-sm text-muted-foreground hover:text-foreground"
            >
              {link.label}
            </a>
          {/each}
        </div>
      </nav>
    </div>
  {/if}
</header>

// components/Header.tsx
'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Menu, Search, X } from 'lucide-react'
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { CATEGORIES } from '@/constants'

export function Header() {
  const [isSearchVisible, setIsSearchVisible] = useState(false)

  return (
    <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container flex h-14 items-center">
        <div className="mr-4 hidden md:flex">
          <Link href="/" className="mr-6 flex items-center space-x-2">
            <span className="hidden font-bold sm:inline-block">
              Gaming Peripherals Review
            </span>
          </Link>
          <nav className="flex items-center space-x-6 text-sm font-medium">
            <Link href="https://twitter.com">Twitter</Link>
            <Link href="https://instagram.com">Instagram</Link>
            <Link href="https://tiktok.com">TikTok</Link>
          </nav>
        </div>
        <Button
          variant="ghost"
          className="mr-2 px-0 text-base hover:bg-transparent focus-visible:bg-transparent focus-visible:ring-0 focus-visible:ring-offset-0 md:hidden"
          onClick={() => setIsSearchVisible(!isSearchVisible)}
        >
          <Search className="h-5 w-5" />
          <span className="sr-only">Search</span>
        </Button>
        <div className="flex flex-1 items-center justify-between space-x-2 md:justify-end">
          <div className={`flex-1 md:flex ${isSearchVisible ? 'flex' : 'hidden'}`}>
            <Input
              placeholder="Search products..."
              className="h-9 md:w-[300px] lg:w-[400px]"
            />
          </div>
          <nav className="flex items-center">
            <Sheet>
              <SheetTrigger asChild>
                <Button
                  variant="ghost"
                  className="px-0 text-base hover:bg-transparent focus-visible:bg-transparent focus-visible:ring-0 focus-visible:ring-offset-0 md:hidden"
                >
                  <Menu className="h-5 w-5" />
                  <span className="sr-only">Toggle Menu</span>
                </Button>
              </SheetTrigger>
              <SheetContent side="left">
                <nav className="flex flex-col space-y-4">
                  <Link href="https://twitter.com">Twitter</Link>
                  <Link href="https://instagram.com">Instagram</Link>
                  <Link href="https://tiktok.com">TikTok</Link>
                </nav>
              </SheetContent>
            </Sheet>
          </nav>
        </div>
      </div>
      <div className="container mt-2">
        <Tabs defaultValue={CATEGORIES[0]} className="w-full">
          <TabsList className="w-full justify-start">
            {CATEGORIES.map((category) => (
              <TabsTrigger key={category} value={category} className="flex-1">
                {category}
              </TabsTrigger>
            ))}
          </TabsList>
        </Tabs>
      </div>
    </header>
  )
}
