// components/ProductCard.tsx
import Image from "next/image";
import Link from "next/link";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Product } from "@/types";
import { formatPrice, getRatingEmoji } from "@/utils";
import { KeyboardPost, MousepadPost, MousePost } from "@/lib/prismic";

export function ProductCard({ product }: { product: Product }) {
  const isMousePost = "mouse_name" in product.data;
  const isMousepadPost = "mousepad_name" in product.data;
  const isKeyboardPost = "keyboard_name" in product.data;

  let name = "Unknown Product";
  let image = { url: "/placeholder.svg", alt: "Product Image" };
  let shape = "N/A";
  let currentProduct = product;

  if (isMousePost) {
    const mouse = product as MousePost;
    name = mouse.data.mouse_name_short;
    image = mouse.data.mouse_image;
    shape = mouse.data.mouse_shape_type;
  }

  if (isMousepadPost) {
    const mousepad = product as MousepadPost;
    name = mousepad.data.mousepad_name;
    image = mousepad.data.mousepad_image;
    shape = "N/A";
  }

  if (isKeyboardPost) {
    const keyboard = product as KeyboardPost;
    name = keyboard.data.keyboard_name;
    image = keyboard.data.image;
    shape = "N/A";
  }

  const [minPrice, maxPrice] = product.data.price_range
    .split("-")
    .map((price) => parseInt(price.replace(/\D/g, "")));

  return (
    <Card className="overflow-hidden">
      <CardContent className="p-0">
        <div className="relative aspect-square">
          <Image
            src={image.url}
            alt={image.alt || name}
            fill
            className="object-cover"
            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
            loading="lazy"
          />
        </div>
        <div className="p-4">
          <h3 className="font-semibold truncate">{name}</h3>
          <div className="flex items-center justify-between mt-1">
            <span className="text-sm">
              {getRatingEmoji(parseInt(product.data.value_rating))}
            </span>
            {isMousePost && <Badge variant="secondary">{shape}</Badge>}
          </div>
          <p className="mt-2 text-sm text-muted-foreground">
            {formatPrice(minPrice)} - {formatPrice(maxPrice)}
          </p>
        </div>
      </CardContent>
      <CardFooter className="grid grid-cols-2 gap-2 p-4">
        <Button asChild variant="secondary" className="w-full">
          <Link href={product.data.review_content_embed.embed_url ?? "#"}>
            Watch Review
          </Link>
        </Button>
        <Button asChild variant="default" className="w-full">
          <Link href={product.data.affiliate_link.url ?? "#"}>Check Price</Link>
        </Button>
      </CardFooter>
    </Card>
  );
}

// src/lib/components/ProductCard.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button";
  import { getRatingEmoji, formatPrice } from "$lib/utils";
  import type { Mouse, Mousepad, Keyboard } from "$lib/types/prismic";

  export let product: Mouse | Mousepad | Keyboard;
  export let type: "mouse" | "mousepad" | "keyboard";

  $: image = type === "mousepad" 
    ? product.data.mousepad_image 
    : type === "keyboard" 
    ? product.data.image 
    : product.data.mouse_image;

  $: name = type === "mousepad" 
    ? product.data.mousepad_name 
    : type === "keyboard" 
    ? product.data.keyboard_name 
    : product.data.mouse_name_short;

  $: shape = type === "mouse" ? product.data.mouse_shape_type : undefined;
</script>

<div class="group relative overflow-hidden rounded-lg border bg-card p-4">
  <div class="aspect-square overflow-hidden rounded-md">
    <img
      src={image.url}
      alt={image.alt}
      class="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
      loading="lazy"
    />
  </div>

  <div class="mt-4 space-y-2">
    <div class="flex items-center justify-between">
      <h3 class="font-medium">{name}</h3>
      <span class="text-sm">{getRatingEmoji(parseInt(product.data.value_rating))}</span>
    </div>

    {#if shape}
      <span class="inline-block rounded-full bg-muted px-2.5 py-0.5 text-xs">
        {shape}
      </span>
    {/if}

    <p class="text-sm text-muted-foreground">
      {product.data.price_range}
    </p>

    <div class="flex gap-2">
      <Button
        variant="secondary"
        size="sm"
        class="w-full"
        href={product.data.review_content_embed.embed_url}
        target="_blank"
        rel="noopener noreferrer"
      >
        Watch Review
      </Button>
      <Button
        variant="default"
        size="sm"
        class="w-full"
        href={product.data.affiliate_link.url}
        target="_blank"
        rel="noopener noreferrer"
      >
        Check Price
      </Button>
    </div>
  </div>
</div>
